version: '3.7'
services:
  vacancy-nginx:
    build:
      context: ./docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8086:80"
    depends_on:
      - vacancy-php-fpm

  vacancy-php-fpm:
    build:
      context: ./docker
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - vacancy-postgres

  vacancy-php-cli:
    build:
      context: ./docker
      dockerfile: dev/php-cli/Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - vacancy-postgres
    working_dir: /app
    tty: true

  vacancy-postgres:
    image: postgres:11.2-alpine
    volumes:
      - vacancy-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  vacancy-swagger:
    build:
      context: ./docker
      dockerfile: dev/swagger/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8085:80"

volumes:
  composer:
  vacancy-postgres:
